export const customQueryKey = {
  auth: { getMe: "get-me" },
  courtrooms: {
    mine: "my-courtrooms",
    summary: "courtroom-summary",
    timeline: "status-timeline",
    all: "all-courtrooms",
    divisions: "divisions",
  },
  causeList: { byCourtroom: "cause-list" },
  diary: { byCourtroom: "diary" },
  broadcasts: { all: "broadcasts" },
  dateRequests: { all: "date-requests" },
  alerts: { all: "alerts" },
  activity: { all: "activity" },
  admin: {
    overview: "admin-overview",
    registrars: "admin-registrars",
    lawyers: "admin-lawyers",
    judges: "judges",
    assignments: "judge-assignments",
    calendar: "calendar",
    consensus: "consensus",
  },
} as const;
